name: hisepy
channels:
  - conda-forge
  - bioconda
  - plotly
  - defaults
dependencies:
  - python=3.11
  - autopep8
  - build
  - conda-build
  - flake8
  - google-cloud-storage
  - grayskull
  - h5py
  - isort
  - numpy
  - pandas==2.1.0
  - pip
  - plotly==5.12.0
  - pyreadr
  - pytest
  - PyYAML
  - requests
  - termcolor
  - toml
  - twine
  - pip:
    - flake8
    - pipreqs
    - pip-tools